# Agent/Quality_loop/kg_manager.py
import networkx as nx
import json
import os
import itertools

class KGManager: # ✅ Class name matches quality_loop.py import
    def __init__(self, save_path="loop_knowledge_base.json"):
        """
        Initialize the Knowledge Graph Manager
        :param save_path: Local path to save/load the graph JSON
        """
        # Use Directed Graph
        self.graph = nx.DiGraph()
        self.save_path = save_path
        
        # Load existing graph if available, otherwise initialize default rules
        if os.path.exists(save_path):
            try:
                self.load_graph()
                print(f"✅ Loaded local Knowledge Graph: {save_path}")
            except Exception as e:
                print(f"⚠️ Load failed, re-initializing graph: {e}")
                self._init_basic_rules()
        else:
            self._init_basic_rules()

    def add_relation(self, source, target, relation_type):
        """
        Add a knowledge triplet: Source --[relation]--> Target
        """
        self.graph.add_edge(source, target, relation=relation_type)

    def _init_basic_rules(self):
        """
        Fallback initialization only used if JSON is missing.
        Since you have a perfect JSON now, this is just a backup.
        """
        print("🌱 Initializing Basic Rules (Fallback)...")
        self.add_relation("High Crystallinity", "Water Diffusion", "inhibits")
        # ... (rest can be kept as minimal backup)

    def check_fact_validity(self, text_answer: str):
        """
        Interface called by Quality Loop.
        Extracts known entities from the text answer and checks logical consistency.
        :param text_answer: The text generated by RAG/LLM
        :return: (is_valid: bool, reason: str)
        """
        if not text_answer:
            return True, "Skipped: Empty answer."

        # 1. Simple Entity Linking
        # Scan text to see if graph nodes appear in it (case-insensitive)
        found_keywords = []
        lower_text = text_answer.lower()
        
        for node in self.graph.nodes():
            # Check if node name or its alias appears in text
            node_data = self.graph.nodes[node]
            alias = node_data.get("alias", "").lower()
            
            if node.lower() in lower_text or (alias and alias in lower_text):
                found_keywords.append(node)
        
        # Deduplicate
        found_keywords = list(set(found_keywords))

        # If fewer than 2 keywords found, cannot check relationships
        if len(found_keywords) < 2:
            return True, f"KG Pass: Not enough recognized entities found ({found_keywords})."

        # 2. Call core consistency check
        conflicts, logs = self.check_consistency(found_keywords)

        # 3. Construct result
        if conflicts:
            # Direct Conflict found
            reason = "KG Found Conflicts:\n" + "\n".join(conflicts)
            return False, reason
        
        if logs:
            # Trade-off Warning found -> Treated as BLOCKING factor here
            reason = "KG Found Trade-off Risks:\n" + "\n".join(logs)
            return False, reason

        return True, f"KG Pass: Verified logic among {found_keywords}"

    def check_consistency(self, design_claims: list):
        logs = []
        conflicts = []
        
        # 🔥 CRITICAL UPDATE: 定义负面关系词汇表 (必须与 JSON 里的词汇对应)
        negative_relations = [
            "inhibits", 
            "reduces", 
            "conflicts_with", 
            "prevents", 
            "inhibits_entry",       # Polyanhydride 特有
            "extends_timeline_of"   # High MW 特有
        ]
        
        # 🔥 CRITICAL UPDATE: 定义正面关系词汇表 (用于调试或未来扩展)
        positive_relations = [
            "promotes", 
            "leads_to", 
            "favors",               # Amorphous -> Hydrolysis
            "produces", 
            "triggers", 
            "causes",
            "creates",
            "susceptible_to",
            "highly_susceptible_to",
            "strongly_promotes",
            "has_property",
            "strongly_has_property",
            "can_have",
            "contains",
            "degradation_mode",
            "dominates_property",
            "is_entirely",
            "moderately_has_property",
            "produces_significant"
        ]

        for prop_a, prop_b in itertools.combinations(design_claims, 2):
            pairs_to_check = [(prop_a, prop_b), (prop_b, prop_a)]
            
            for src, dst in pairs_to_check:
                try:
                    # Search for paths up to 4 steps deep
                    for path in nx.all_simple_paths(self.graph, source=src, target=dst, cutoff=4):
                        relations = []
                        path_details = []
                        
                        for i in range(len(path)-1):
                            u, v = path[i], path[i+1]
                            rel = self.graph[u][v].get('relation', 'unknown')
                            relations.append(rel)
                            path_details.append(f"[{u}]--({rel})-->[{v}]")
                        
                        # Count negatives
                        neg_count = sum(1 for r in relations if r in negative_relations)
                        
                        # Logic: Odd negatives = Overall Inhibition/Negative Correlation
                        is_negative_chain = (neg_count % 2 != 0)
                        
                        if is_negative_chain:
                            chain_str = " ".join(path_details)
                            msg = (f"⚠️ [Logic Conflict] Path Analysis:\n"
                                   f"   Path: {chain_str}\n"
                                   f"   Logic: {neg_count} negative steps => Overall INHIBITION.\n"
                                   f"   Result: '{src}' implies reducing/inhibiting '{dst}'.")
                            logs.append(msg)

                except nx.NetworkXNoPath:
                    continue
            
            # Check direct conflicts (Mutual Exclusivity)
            if self.graph.has_edge(prop_a, prop_b):
                if self.graph[prop_a][prop_b]['relation'] == "conflicts_with":
                    conflicts.append(f"❌ [Direct Conflict] '{prop_a}' and '{prop_b}' are mutually exclusive.")
            if self.graph.has_edge(prop_b, prop_a):
                if self.graph[prop_b][prop_a]['relation'] == "conflicts_with":
                    conflicts.append(f"❌ [Direct Conflict] '{prop_b}' and '{prop_a}' are mutually exclusive.")

        return conflicts, logs

    def visualize(self):
        """Visualize Graph using Matplotlib"""
        try:
            import matplotlib.pyplot as plt
        except ImportError as e:
            print(f"❌ Cannot import Matplotlib: {e}")
            return

        try:
            plt.figure(figsize=(14, 12)) # Make figure larger
            pos = nx.spring_layout(self.graph, seed=42, k=0.8) # Increase k to spread nodes
            
            nx.draw_networkx_nodes(self.graph, pos, node_color='lightgreen', node_size=1500, alpha=0.9)
            nx.draw_networkx_labels(self.graph, pos, font_size=8, font_weight='bold')
            nx.draw_networkx_edges(self.graph, pos, arrows=True, arrowsize=15, edge_color='gray', alpha=0.6)
            
            edge_labels = nx.get_edge_attributes(self.graph, 'relation')
            nx.draw_networkx_edge_labels(self.graph, pos, edge_labels=edge_labels, font_size=7)
            
            plt.title("Biodegradable Polymer Knowledge Graph", fontsize=16)
            plt.axis('off')
            plt.tight_layout()
            plt.show()
        except Exception as e:
            print(f"Visualization failed: {e}")

    def save_graph(self):
        """Save graph to JSON"""
        data = nx.node_link_data(self.graph)
        try:
            with open(self.save_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"💾 Graph saved to: {self.save_path}")
        except Exception as e:
            print(f"❌ Save failed: {e}")

    def load_graph(self):
        """Load graph from JSON"""
        with open(self.save_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        self.graph = nx.node_link_graph(data)

if __name__ == "__main__":
    kg = KGManager()
    
    print("\n" + "="*60)
    print("🧪 Test Scenario: Verifying Logic Consistency")
    print("="*60)
    
    # Test 1: Check if High Crystallinity conflicts with Degradation Rate (should warn)
    # Logic: High Cryst -> inhibits Water -> promotes Hydrolysis -> promotes Deg rate
    # Result: inhibits (negative) * promotes (positive) * promotes (positive) = Negative
    user_intent = ["High Crystallinity", "Degradation Rate"]
    print(f"📝 Testing Keywords: {user_intent}")
    
    conflicts, logs = kg.check_consistency(user_intent)
    
    print("\n📊 Verification Report:")
    if conflicts:
        for c in conflicts: print(c)
    
    if logs:
        for l in logs: print(l)
    else:
        print("✅ Logic Consistent (No Trade-offs found)")